### PR TITLE
Fix a static analysis warning

### LINKED ISSUE #589: [BUG] `parse_variant()` may inadvertently move lvalues
**Describe the bug**
reply.h:312:36: forwarding reference passed to std::move()

**To Reproduce**
Make sure a non-`const` lvalue is processed. The
```
template< class T >
constexpr variant( T&& t )
```
constructor of the `Variant` will be used which will forward that to the constructor of the matching type.

**Expected behavior**
Expecting non-temporaries to be copied instead of moved. That is, use `std::forward` instead of `std::move`

### PR DESCRIPTION
**Pull request by TedLyngmo**
`reply.h`: `std::move` was used where `std::forward` should be used

Fixes #589

### CODE REVIEW

File: src/sw/redis++/connection_pool.cpp [hunk 1]
```diff
@@ -55,13 +55,13 @@ ConnectionPool::ConnectionPool(SimpleSentinel sentinel,
     assert(_sentinel);
 }
 
-ConnectionPool::ConnectionPool(ConnectionPool &&that) {
+ConnectionPool::ConnectionPool(ConnectionPool &&that) noexcept {
```
Comment (sewenew) [inline src/sw/redis++/connection_pool.cpp:58]: Both `std:::lock_guard` and `std::lock` do not have `noexcept` specifier. I don't think it's a good idea to add `noexcept` for `ConnectionPool`'s constructor and assignment operator.

**Comment by sewenew** [comment]
Thanks for your contributing!

Could you revert the noexcept change, and I'll merge your PR.

Thanks again!

**Comment by sewenew** [comment]
> The failure to build on Windows seems unrelated to this patch:
> 
> ```
> CMake Error at test/CMakeLists.txt:10 (find_path):
>   Could not find HIREDIS_HEADER using the following files: hiredis
> ```

Yes. The Windows build failure has nothing to do with your PR.

File: src/sw/redis++/connection_pool.cpp (hunk 1 above)
Comment (TedLyngmo) [reply src/sw/redis++/connection_pool.cpp]: Ah, good point and I don't have a clean solution other than catching any `system_error` and `std::terminating` :-) Removing that part.
